### ISSUE TITLE
datastore locked

### ISSUE THREAD

**Issue by amazingAmy** [CESNET/netopeer#101] opened 2016-03-24 07:16 UTC
I want to edit the running datastore，my system is centos release 6.3
so the procedure is 

```
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-3" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<lock>
<target>
<running/>
</target>
</lock>
</rpc>
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Adding new event (0)
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-3">
  <ok/>
</rpc-reply>
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-4" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<lock>
<target>
<candidate/>
</target>
</lock>
</rpc>
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Adding new event (0)
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-4">
  <ok/>
</rpc-reply>
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-5" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<edit-config>
<target>
<candidate/>
</target>
<default-operation>none</default-operation>
<error-option>rollback-on-error</error-option>
<config>
<interfaces xmlns="urn:sdnhub:odl:tutorial:router" xmlns:a="urn:ietf:params:xml:ns:netconf:base:1.0" a:operation="replace">
<id>eth0</id>
<ip-address>10.10.1.1/24</ip-address>
</interfaces>
</config>
</edit-config>
</rpc>
netopeer-server[30489]: Creating the node interfaces (src/datastore/edit_config.c:1492)
netopeer-server[30489]: Deleting the node interfaces (src/datastore/edit_config.c:1008)
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-5">
  <ok/>
</rpc-reply>
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-6" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<commit/>
</rpc>
netopeer-server[30489]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[30489]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[30489]: Transapi calling callback /A:netopeer/A:modules/A:module/A:enabled with op REM.
netopeer-server[30489]: Adding new event (3)
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-6">
  <ok/>
</rpc-reply>
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-7" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<unlock>
<target>
<candidate/>
</target>
</unlock>
</rpc>
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Adding new event (0)
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-7">
  <ok/>
</rpc-reply>
netopeer-server[30489]: Received message (session 29): <?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-8" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<unlock>
<target>
<running/>
</target>
</unlock>
</rpc>
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Adding new event (0)
netopeer-server[30489]: Created dummy session 0 for user 'root' (UID 0) - recovery session
netopeer-server[30489]: Writing message (session 29): <?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="m-8">
  <ok/>
</rpc-reply>
```

In short, the procedure is:
**lock running
lock candidate
edit-config candidate
commit
unlock candidate
unlock running**

I think it is a good way to edit the running datestore's info, but when I connect the netopeer server through `netopeer-cli`, `get-config running`,  **the result is null !**

then I check the xml which stores the data, the information is:
```
<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="29" locktime="2016-03-24T20:40:54Z">
    <interfaces xmlns="urn:sdnhub:odl:tutorial:router">
      <id>eth0</id>
      <ip-address>10.10.1.1/24</ip-address>
    </interfaces>
  </running>
  <startup lock=""/>
  <candidate modified="true" lock="29" locktime="2016-03-24T20:40:54Z">
    <interfaces xmlns="urn:sdnhub:odl:tutorial:router">
      <id>eth0</id>
      <ip-address>10.10.1.1/24</ip-address>
    </interfaces>
  </candidate>
</datastores>
```
I found that running and candidate are locked, and when I `get-config running` **there is nothing**
when I execute `unlock`, the result is nothing to unlock.
 I wonder how to make the datastores unlocked, and why the datastores is locked.

and then I restart the server with `netopeer-server -v 3`, I found the running datastore is empty, but the candidate is 
```
  <candidate modified="false" lock="" locktime="">
    <ipv6-twod-routing xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv6-twod-routing">
      <twod-list>
        <destination-prefix>2000::/3</destination-prefix>
        <source-prefix>2001:db8:1::/48</source-prefix>
        <cost>2</cost>
      </twod-list>
      <enabled>true</enabled>
    </ipv6-twod-routing>
  </candidate>
```

then I excute `commit` in `netopeer-cli`, the result is "ok", and the xml is
```
<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="" locktime="">
    <ipv6-twod-routing xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv6-twod-routing">
      <twod-list>
        <destination-prefix>2000::/3</destination-prefix>
        <source-prefix>2001:db8:1::/48</source-prefix>
        <cost>2</cost>
      </twod-list>
      <enabled>true</enabled>
    </ipv6-twod-routing>
  </running>
  <startup lock=""/>
  <candidate modified="false" lock="" locktime="">
    <ipv6-twod-routing xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv6-twod-routing">
      <twod-list>
        <destination-prefix>2000::/3</destination-prefix>
        <source-prefix>2001:db8:1::/48</source-prefix>
        <cost>2</cost>
      </twod-list>
      <enabled>true</enabled>
    </ipv6-twod-routing>
  </candidate>
</datastores>
```
the xml seems fine, but when I `get-config running`, **the result is empty!**

maybe does the `get-config` have any problem? 
Any answer will be appreciate!

**Comment by amazingAmy** [comment] 2016-03-24 14:02
@mirekys

**Comment by michalvasko** [comment] 2016-03-24 14:34
Hi,
you are doing something wrong, beacuse I followed your steps (lock running, lock candidate, edit-config candidate, commit, unlock candidate, unlock running) and it worked exactly as expected. I finished with the changes reflected in *running* and both *running* and *candidate* unlocked. I did all this in one session using **netopeer-cli**. Did you do it some other way? What do you mean the result of `get-config running` is empty, it outputs at least `Result:` or not?

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-24 15:32
it outputs  `Result:`, but doesn't have any contents.
Actually I upload 3 modules in my device, and I use the OPENDAYLIGHT‘s RESTful API to edit the message, 
`curl -u admin:admin -v -X PUT -H "Content-Type: application/xml" -d '
      <interfaces xmlns="urn:sdnhub:odl:tutorial:router">
        <id>eth0</id>
        <ip-address>10.10.1.1/24</ip-address>
      </interfaces>
' http://localhost:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/router/yang-ext:mount/router:interfaces/eth0
`
then I check the** netopeer-server -v 3** output, I found the procedure as I have said.
but I think the xml is correct, then` get-config running`  should output the xml content, I don't know why there is only `Result:`

**Comment by amazingAmy** [comment] 2016-03-24 15:50
maybe the netopeer I have installed has some error, but in the `netopeer-server -v 3`,there is nothing about error. 
I restart the** netopeer server**, the running datastore is rewrited, but the candidate datastore has any change,
`  <candidate modified="false" lock="" locktime="">
    <ipv6-twod-routing xmlns="urn:ietf:params:xml:ns:yang:ietf-ipv6-twod-routing">
      <twod-list>
        <destination-prefix>2000::/3</destination-prefix>
        <source-prefix>2001:db8:1::/48</source-prefix>
        <cost>2</cost>
      </twod-list>
      <enabled>true</enabled>
    </ipv6-twod-routing>
  </candidate>`

the lock message disappeared, and then I **commit** using netopeer-cli, the xml is
`<?xml version="1.0" encoding="UTF-8"?>
<datastores xmlns="urn:cesnet:tmc:datastores:file">
  <running lock="" locktime="">
    <interfaces xmlns="urn:sdnhub:odl:tutorial:router">
      <id>eth0</id>
      <ip-address>10.10.1.1/24</ip-address>
    </interfaces>
  </running>
  <startup lock=""/>
  <candidate modified="false" lock="" locktime="">
    <interfaces xmlns="urn:sdnhub:odl:tutorial:router">
      <id>eth0</id>
      <ip-address>10.10.1.1/24</ip-address>
    </interfaces>
  </candidate>
</datastores>`

then I execute `get-config` the result is：
![image](https://cloud.githubusercontent.com/assets/18045341/14022520/231ee818-f21b-11e5-907e-735c478979c5.png)

**Comment by amazingAmy** [comment] 2016-03-24 15:51
@michalvasko  I beg for your reply！

**Comment by michalvasko** [comment] 2016-03-29 10:12
Hi,
this quite weird and it's hard to help you when I am unable to replicate your issue. So, could you please go step-by-step and include the command, the result, and the datastore file content (of all your modules) of each step? Until you get the get-config you have posted here. Thanks.

Regards,
Michal

PS: There were Easter holidays here, so sorry for not replying.

**Comment by amazingAmy** [comment] 2016-03-29 15:57
Thank you for your help!!
first of all，my system is CentOS 6.3，with the core is 2.6.32, the system info as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14114222/c61f9666-f608-11e5-8309-fdb89bf06298.png)
now I use the command : `netopeer-manager add --name Routing --model ietf-ipv6-twod-routing.yin --datastore /usr/local/etc/netopeer/cfgnetopeer/routing.xml` to load a module.
then `netopeer-server -v 3`, the output is 
![image](https://cloud.githubusercontent.com/assets/18045341/14114322/14135768-f609-11e5-97b8-5d9b4b66a330.png)
now the file** routing.xml ** info is:
![image](https://cloud.githubusercontent.com/assets/18045341/14114362/3d21d922-f609-11e5-89a5-446d2a7daf4c.png)
meanwhile, I input `get-config` command using **netopeer-cli**,the result is:
![image](https://cloud.githubusercontent.com/assets/18045341/14114444/8bb5b2d4-f609-11e5-89a8-2e11c0fb0ec4.png)
and the log is 
![image](https://cloud.githubusercontent.com/assets/18045341/14114517/d1c3fe20-f609-11e5-9330-2d92a7379134.png)
![image](https://cloud.githubusercontent.com/assets/18045341/14114529/dffea12a-f609-11e5-82b1-1883cc40d65a.png)
![image](https://cloud.githubusercontent.com/assets/18045341/14114543/eb53fcbe-f609-11e5-9a00-02031f7c95dd.png)

**Comment by amazingAmy** [comment] 2016-03-29 16:03
Then I use the `lock running` and `lock candidate` ,as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14114659/5fbf4bb2-f60a-11e5-9012-1c5191c6e815.png)
the **routing.xml**'s info is 
![image](https://cloud.githubusercontent.com/assets/18045341/14114677/7c2dbfea-f60a-11e5-998c-1858086c83cd.png)
and the log is
![image](https://cloud.githubusercontent.com/assets/18045341/14114690/8f33c1a2-f60a-11e5-9381-16d4d47d42ac.png)

then I use `get-config` to get the datastores' info.
the result is
![image](https://cloud.githubusercontent.com/assets/18045341/14114727/bf315be4-f60a-11e5-9eac-619b554058ff.png)

**Comment by amazingAmy** [comment] 2016-03-29 16:09
then I `edit-config candidate`
the edit content is 
![image](https://cloud.githubusercontent.com/assets/18045341/14114776/006ab1a0-f60b-11e5-8aaf-8d93786b3d3c.png)
and **ok** is returned.
now the **routing.xml** 's info is:
![image](https://cloud.githubusercontent.com/assets/18045341/14114830/442c835a-f60b-11e5-838b-7d8156a9dc13.png)
the log is:
![image](https://cloud.githubusercontent.com/assets/18045341/14114851/54f76416-f60b-11e5-9dfd-87a2fbb9d55b.png)

here I use `get-config` again:
![image](https://cloud.githubusercontent.com/assets/18045341/14114917/93cc6a92-f60b-11e5-9c5e-436b393099e7.png)

so far, everything seems well.

**Comment by amazingAmy** [comment] 2016-03-29 16:15
now I input `commit` using **netopeer-cli**, the result is 
![image](https://cloud.githubusercontent.com/assets/18045341/14115007/e300cf0e-f60b-11e5-95f8-86b34eaa8e58.png)
meanwhile the `routing.xml`'s info is
![image](https://cloud.githubusercontent.com/assets/18045341/14115027/fac4e814-f60b-11e5-9a58-0bba017e13c2.png)
the log is
![image](https://cloud.githubusercontent.com/assets/18045341/14115050/0b21bb56-f60c-11e5-8901-2752cd833dd0.png)
but when I `get-config running` or `get-config candidate`, **the result is null**,as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14115097/39f26bb0-f60c-11e5-82bc-e8dc4bd984fe.png)
at the same time, there are something output in the log:
![image](https://cloud.githubusercontent.com/assets/18045341/14115152/6a6eee8a-f60c-11e5-9d7d-52032abf9fbd.png)

**I don't know why there is nothing when I get-config running or candidate!**

**Comment by amazingAmy** [comment] 2016-03-29 16:21
here I want to edit the candidate again, the content as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14115250/ce23f4de-f60c-11e5-9ce6-3fe4af790395.png)
but when I quit the edit, the result is:
![image](https://cloud.githubusercontent.com/assets/18045341/14115286/e82dbcac-f60c-11e5-96ce-5c11d4542c6c.png)

and the log is:
![image](https://cloud.githubusercontent.com/assets/18045341/14115315/00646438-f60d-11e5-80e3-09854f340ce5.png)
and the routing.xml is not changed,
![image](https://cloud.githubusercontent.com/assets/18045341/14115329/1835d09c-f60d-11e5-95cc-d3f6fb270272.png)

**so I infer that the `commit` demand makes something wrong.**

**Comment by amazingAmy** [comment] 2016-03-29 16:24
finally, I `unlock candidate` and `unlock running`,
![image](https://cloud.githubusercontent.com/assets/18045341/14115393/62765474-f60d-11e5-9755-007a814a83b0.png)
but the commands couldn't affect the **routing.xml**, the routing.xml is
![image](https://cloud.githubusercontent.com/assets/18045341/14115432/8e45415a-f60d-11e5-9f43-aad5821c57f0.png)
 meanwhile the log is:
![image](https://cloud.githubusercontent.com/assets/18045341/14115455/ac657240-f60d-11e5-9e28-2291059b60c7.png)

**Comment by amazingAmy** [comment] 2016-03-29 16:28
In addition, I did another experiment,
I just `edit-config candidate`, and `commit`,  then `get-config running` , `get-config candidate`.
the result is as the same as above, there is nothing but `Result:`
![image](https://cloud.githubusercontent.com/assets/18045341/14115576/1919f42e-f60e-11e5-9109-184ffb7e6112.png)

I think maybe the `commit` command make something wrong in CentOS 6.3, what do you think?

**Comment by amazingAmy** [comment] 2016-03-29 16:29
@michalvasko thank you for your help!!

**Comment by michalvasko** [comment] 2016-03-30 07:27
Hi,
right after you add your module and issue `get-config` on all the datastores, you get empty *candidate*, which is wrong and you should get the same data as in *running*. Please look into `/etc/netopeer/cfgnetopeer/datastore.xml` and `/etc/netopeer/cfgnetopeer/datastore-server.xml` and check the attributes on the *candidate* datastores (subtrees). If there are any locks, then remove them manually. The safest would probably be to just replace the `<candidate>` subtree with this:

```
<candidate modified="false" lock=""/>
```

It is possible something was left over from some previous sessions if *netopeer-server* was incorrectly terminated, but during standard use this should not happen. If this won't help then you can also simply delete all the datastores, they will be created with the correct default content. Plase try this and then try to get-config the *candidate* datastore.

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-30 07:56
hi, thank you for your answer.
I check the he attributes on the candidate datastores in `/etc/netopeer/cfgnetopeer/datastore.xml` and `/etc/netopeer/cfgnetopeer/datastore-server.xml`. 
`datastore.xml` is
![image](https://cloud.githubusercontent.com/assets/18045341/14135288/3a525eca-f68f-11e5-8e29-32ca1cb01524.png)
and the `datastore-server.xml` is
![image](https://cloud.githubusercontent.com/assets/18045341/14135305/4b0550ba-f68f-11e5-9747-eefafb23c4d7.png)
there is nothing about lock.
In addition, I often use `kill -9` to terminate _netopeer-server_, because I don't know the **stop or restart command**, is there any documents?

**Comment by amazingAmy** [comment] 2016-03-30 07:58
@michalvasko

**Comment by michalvasko** [comment] 2016-03-30 08:10
Hi,
please just press `Ctrl + C` in the terminal with *netopeer-server* (or you can send *SIGINT* instead *SIGKILL*), it will then exit the way it should. I am wondering why you have *XML 2.0* specified in `datastore-server.xml`. Anyway, try removing both those files, connect to the server, and issue `get-config candidate`. You should get the same content as what is in the running.

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-30 08:15
Now I `netopeer-manager rm --name Routing`, and delete the files: 
`/etc/netopeer/cfgnetopeer/routing.xml`
`/etc/netopeer/cfgnetopeer/datastore.xml`
`/etc/netopeer/cfgnetopeer/datastore-server.xml`
and then `netopeer-manager add --name Routing --model ietf-ipv6-twod-routing.yin --datastore /usr/local/etc/netopeer/cfgnetopeer/routing.xml`
`netopeer-server -v 3`
also I `get-config`, the candidate is still empty.
![image](https://cloud.githubusercontent.com/assets/18045341/14135721/aee25afe-f691-11e5-8271-dc22e1d3114f.png)

the question isn't resolved.
**Do you think that maybe there is bug with the CentOS 6.3**? 
For I don't have such problem when I use ** Ubuntu 14**
Also I have done such experiments twice using two CentOS 6.3 systems, and the problems are same. when I excute `commit`, the `get-config candidate` & `get-config running` is empty as above.

**Comment by michalvasko** [comment] 2016-03-30 08:23
The problem is I tried it in Scientific Linux 6, which should be almost the same and it worked well. Maybe check what versions of dependencies and libraries you use, perhaps compare them to those used on Ubuntu. I don't know where else could then be the problem. You can also try to send `discard-changes` and then `get-config candidate`, check whether it will make any difference.

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-30 08:24
Hi, I changed the datastore-server.xml by carelessness, and then I recovered the file.

**Comment by michalvasko** [comment] 2016-03-30 08:32
So it works now as expected?

**Comment by amazingAmy** [comment] 2016-03-30 08:37
Hi, when I send `discard-changes`, the candidate is the same as running.
![image](https://cloud.githubusercontent.com/assets/18045341/14136341/fb21b600-f694-11e5-970a-30caf2bc7260.png)
and then I send `edit-config candidate` , `commit`, `get-config candidate`, `get-config running`
the result is
![image](https://cloud.githubusercontent.com/assets/18045341/14136388/443a9622-f695-11e5-916c-f3a65f766b2f.png)

here I have 2 questions.
1、I wonder what's the meaning of `discard-changes`, and why I have such problem.
2、when I send `get-config running` or `get-config candidate`, there is still something about module's info as I marked in the picture.

**Comment by michalvasko** [comment] 2016-03-30 08:45
`discard-changes` simply resets the *candidate* datastore to be the same as the *running* datastore, but that should be so by default when starting *netopeer-server*. You should read about it in the [NETCONF RFC](http://tools.ietf.org/html/rfc6241#section-8.3.4.2). Result of both `get-config` commands is correct, they return a merged configuation of all the modules (by default you have 2, your *netconf-server* configuration is empty, you can see *netopeer* configuration right there, and also *ipv6-twod-routing*). But you need to know these things, please read the RFC I referenced carefully. We are here to help with any technical problems you may have with our software, not to explain basics of NETCONF protocol functioning.

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-30 08:51
Ok, thank you very much!!
Finally, I wonder is there any problems when I use 2 sessions to control the `netopeer-server`?

**Comment by michalvasko** [comment] 2016-03-30 08:54
No, you can safely do that, but you should use locks if you want to make sure one session will not change something the other session works with. Also, we think your *candidate* datastore content was wrong because you were sending SIGKILL to the server, which then could not correctly exit.

Regards,
Michal

**Closed by michalvasko** 2016-03-30 08:54 UTC

**Comment by amazingAmy** [comment] 2016-03-30 08:56
![image](https://cloud.githubusercontent.com/assets/18045341/14136950/125c4dc8-f698-11e5-8f23-214b4f845e8a.png)
 
the running datastore is  unlocked, and why the results are not same when through the session 24 and 21?

**Comment by michalvasko** [comment] 2016-03-30 09:05
Just look at what *session 24* is sending, it includes an empty *filter*, which correctly filters out all the data, that is why the result is empty. *Session 21* does not include any filter, so it receives all the configuration data. All this is written, in the [NETCONF RFC](http://tools.ietf.org/html/rfc6241).

Regards,
Michal

**Comment by amazingAmy** [comment] 2016-03-30 09:41
Thank you very much !
