### ISSUE TITLE
edit-config is not working for cfginterfaces in netopeer

### ISSUE THREAD

**Issue by Barathi07** [CESNET/netopeer#79] opened 2015-12-02 13:11 UTC
Hi,
   I have configured transapi-->cfginterfaces, the get-config command is giving output.
But, when i try edit-config for cfginterfaces, am getting the following error in the NETOPEER-CLI:
"netconf> edit-config running
NETCONF error: operation-failed (application) - Datastore fails to validate (Extra element interfaces-state in interleave)
NETCONF error: operation-failed (application) - Datastore fails to validate (Element data failed to validate content)"
ERROR MSG IN NETOPEER_SERVER LOG:
"netopeer-server[1624]: subdatastore 424238336 fails to validate"
[cfginterfaces_log.txt](https://github.com/CESNET/netopeer/files/49731/cfginterfaces_log.txt)

**Comment by Barathi07** [comment] 2015-12-02 13:17
If i give "validate" command, am getting this error:
netconf> validate running
NETCONF error: operation-failed (application) - Datastore fails to validate (Extra element interfaces-state in interleave)
NETCONF error: operation-failed (application) - Datastore fails to validate (Element data failed to validate content)
If i issue "get-config" command:I got the following:
[get-config.txt](https://github.com/CESNET/netopeer/files/49739/get-config.txt)

**Comment by michalvasko** [comment] 2015-12-03 08:31
Hi,
the important parts are the errors in cfginterfaces_log.txt, they are the reason validation fails. I believe the problem is caused by you having some interfaces that are not fully managed by ifup/ifdown scripts. Then certain parts of interfaces-state fail to be read and in effect are missing in the state configuration. Either that or there was some oversight on our end when we incorrectly assumed that something will be in those configuration files on Debian when it does not have to be. Try to investigate the first suggestion, I will try to look at the second. I take it your distribution is Ubuntu, please correct me if I am wrong.

Regards,
Michal

**Comment by Barathi07** [comment] 2015-12-03 09:31
Yes, you are right.Am working Ubuntu. Even if i try to give the same data, that is displayed in get-config, also not working with edit-config. Got the same error:"Datastore fails to validate"

**Comment by michalvasko** [comment] 2015-12-03 10:51
Hi,
try to pull the latest netopeer, it should be fixed.

Regards,
Michal

**Comment by Barathi07** [comment] 2015-12-03 11:13
okay..will try..thank you..

**Comment by Barathi07** [comment] 2015-12-08 11:09
Thank you so much michal..edit-config is now working for me. I have edited the file "/etc/network/interfaces" to include the missing interfaces.then. it works.

**Closed** 2015-12-08 12:09 UTC

**Comment by DuncanJr** [comment] 2016-06-13 09:48
Hi,
    I include my interfaces (just interface no linking )in "/etc/network/interfaces" . And check the "/etc/network/interfaces.netconf" also involve the content.  But when I want to  modify the device interface ip-address( just interface no linking ) by "edit-config running " ,it show as 
"NETCONF error: operation-failed (application) - Datastore fails to validate (Element config has extra content: interfaces-state)"  .  I check "running config database ", it's  not include this content , what else can I just the device interface IP? 

I use this header "<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">" is work to modify some interface parameter such as "mtu" ,  but use "<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">" will get above mentions error .

Thanks

**Comment by rkrejci** [comment] 2016-06-13 13:59
Please, use the github markdown correctly, parts of your text are not readable.

Regarding the issue of editing running datastore - can you provide the exact content of your edit-config?

**Comment by DuncanJr** [comment] 2016-06-14 01:52
Hi rkrejci,
    ok , I will notice it . 
The following is my edit-config  content of running datastore : 

<interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
   <interface>
      <name>ens37</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
      <oper-status>down</oper-status>
      <last-change>2016-06-13T08:56:29Z</last-change>
      <phys-address>00:0c:29:e7:bd:82</phys-address>
      <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
        <forwarding>false</forwarding>
        <mtu>1300</mtu>
        <address>
          <ip>192.168.1.5</ip>
          <prefix-length>24</prefix-length>
          <origin>other</origin>
        </address>
      </ipv4>
</interface>
</interfaces-state>


thanks

**Comment by DuncanJr** [comment] 2016-06-16 09:16
Hi 
   Since I want to emulate the device status , so I need to try it . 

Thank you for your reply

**Comment by rkrejci** [comment] 2016-06-16 10:45
But with the edit-config, you are trying to change status (read-only) data. The error message is correct, the `interface-state` is not allowed in edit-config.

**Comment by DuncanJr** [comment] 2016-06-20 01:41
OK, I understood, thank you for your reply

**Comment by vinayakpattar** [comment] 2019-07-23 08:50
Hi,
Actually I am using netopeer for ofc-server, I am getting following error.
'NETCONF error: operation-failed (application) - Datastore fails to validate (Extra element logical-switches in interleave)
NETCONF error: operation-failed (application) - Datastore fails to validate (Element capable-switch failed to validate content)'
Where exectly is the error? Please help me out here.
Thanks a lot
Vinayak

**Comment by michalvasko** [comment] 2019-07-23 08:59
Hi Vinayak,
I remember there was a (tedious) way of getting the specific error, but I cannot tell you the exact steps. Sorry, these vague validation errors were one of many reasons we developed [libyang](https://github.com/cesnet/libyang), so use [sysrepo](https://github.com/sysrepo/sysrepo) with [netopeer2](https://github.com/cesnet/netopeer2) to see a specific error. This *netopeer* is not supported anymore.

Regards,
Michal
