### ISSUE TITLE
centOS "commit" has any problem

### ISSUE THREAD

**Issue by amazingAmy** [CESNET/netopeer#102] opened 2016-03-27 16:06 UTC
I load a module on the** CentOS 6.3**, and start up the `netopeer-server -v 3`,  
then I connect server using netopeer-cli, **check the datastors(startup, candidate, running) **as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14066266/937ff792-f477-11e5-9862-25790dcea6da.png)

then I edit the candidate, using `edit-config candidate`, the log is
![image](https://cloud.githubusercontent.com/assets/18045341/14066278/e7419994-f477-11e5-9fd7-3aa863a793cc.png)
It means the edit is successful.
then I input `commit`, the result is "OK", but when I `get-config candidate` and `get-config running`, the result is  `Resulit:`,as follows:
![image](https://cloud.githubusercontent.com/assets/18045341/14066289/3e1ecca0-f478-11e5-9917-6e220c0b2195.png)

but when I check the corresponding xml, I found that the running was changed. It was:
![image](https://cloud.githubusercontent.com/assets/18045341/14066297/71e8ca2c-f478-11e5-9660-80b8241770a0.png)

**I don't know why I `get-config running` , the result is null. Is there a bug in `commit` ?**

I do the same experiment in the **Ubuntu,** everything is well, `get-config running` will output the same content as the xml.

**Comment by amazingAmy** [comment] 2016-03-27 16:07
@mirekys please give me any help, and any advice will be appreciate!

**Comment by michalvasko** [comment] 2016-03-29 10:25
Hi,
I think this may be a duplicate of #101, we will return to it once we solve that one.

Regards,
Michal

**Closed** 2016-03-30 13:20 UTC
